# Generated by Django 5.2.8 on 2026-07-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Gás')),
                ('categoria', models.CharField(choices=[('Medicinal', 'Medicinal'), ('Industrial', 'Industrial')], max_length=20, verbose_name='Categoria')),
                ('capacidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade')),
                ('unidade_medida', models.CharField(choices=[('m³', 'Metros Cúbicos (m³)'), ('kg', 'Quilogramas (kg)'), ('litros', 'Litros')], max_length=10, verbose_name='Unidade de Medida')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras/SKU')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto (Cilindro)',
                'verbose_name_plural': 'Produtos (Cilindros)',
                'ordering': ['nome'],
            },
        ),
    ]
