# Generated by Django 6.0 on 2026-06-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('ENCARREGADO', 'Encarregado'), ('VENDEDOR', 'Vendedor'), ('ATENDENTE', 'Atendente'), ('CARREGADOR', 'Carregador'), ('CLIENTE', 'Cliente')], max_length=25),
        ),
    ]
