# Generated by Django 5.2.8 on 2026-07-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_rota_venda_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_entrega_efetiva',
            field=models.DateField(blank=True, null=True, verbose_name='Data Efetiva de Entrega'),
        ),
        migrations.AddField(
            model_name='venda',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Entrega'),
        ),
    ]
