# Generated by Django 6.0 on 2026-07-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_entrega'),
        ('vendas', '0003_venda_data_entrega_efetiva_venda_prazo_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='rota',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='forma_faturamento',
            field=models.CharField(choices=[('cilindro', 'Por Cilindro'), ('medida', 'Por Medida (m³/kg)')], default='cilindro', max_length=10, verbose_name='Forma de Faturamento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='logistica.entrega', verbose_name='Entrega Associada'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade (Cilindros/Unid)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente (Em Produção/Envase)'), ('Em Separação', 'Em Separação'), ('Em Rota', 'Em Rota de Entrega'), ('Entregue', 'Entregue'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
    ]
