# Generated by Django 5.2.8 on 2026-07-03 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Rota')),
                ('origem', models.CharField(max_length=200, verbose_name='Origem')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distância (km)')),
                ('tempo_estimado_horas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tempo Estimado (h)')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('capacidade_carga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade de Carga (kg)')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Em Manutenção', 'Em Manutenção'), ('Inativo', 'Inativo')], default='Ativo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cobranca', models.CharField(choices=[('Fixo', 'Valor Fixo por Rota'), ('Distancia', 'Por Km Rodado'), ('Peso', 'Por Peso (kg)')], default='Fixo', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Cobrança (R$)')),
                ('rota', models.ForeignKey(blank=True, help_text='Selecione a rota caso seja valor fixo por rota.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fretes', to='logistica.rota')),
            ],
        ),
        migrations.CreateModel(
            name='ManutencaoFrota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateField(verbose_name='Data da Manutenção')),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Total (R$)')),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Em Progresso', 'Em Progresso'), ('Concluída', 'Concluída')], default='Agendada', max_length=20)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='logistica.veiculo')),
            ],
        ),
    ]
