# Generated by Django 6.0 on 2026-07-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_entrega'),
        ('produtos', '0001_initial'),
        ('vendas', '0004_remove_venda_rota_remove_venda_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='localizacao_atual',
            field=models.CharField(choices=[('Base', 'Base'), ('Oficina', 'Oficina'), ('Em Rota', 'Em Rota')], default='Base', max_length=50),
        ),
        migrations.CreateModel(
            name='ValidacaoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_alterada', models.IntegerField(verbose_name='Qtd Alterada (+ ou -)')),
                ('etapa_logistica', models.CharField(max_length=50, verbose_name='Etapa Logística')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='logistica.entrega')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='vendas.venda')),
            ],
        ),
    ]
