# Generated by Django 6.0 on 2026-07-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_veiculo_localizacao_atual_validacaocarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacaocarga',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='logistica.entrega'),
        ),
    ]
